name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable
      track:
        description: "Track of the charm on which we want the promotion to happen. Defaults to latest."
        type: string
        default: 'latest'
        required: false

jobs:
  promote:
    name: Promote
    uses: canonical/observability/.github/workflows/charm-promote.yaml@main
    with:
      promotion: ${{ github.event.inputs.promotion }}
      track: ${{ github.event.inputs.track }}
    secrets: inherit
